title: BLog
description: Explaining Algorithms
theme: just-the-docs
# logo: "your_logo_path"
# favicon_ico: "your_icon_path"

url: https://github.com/Iotguyy/tutorial

aux_links:
  Repository: https://github.com/Iotguyy/tutorial